name: Setup Next.js with Shadcn Component

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: latest

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Create Next.js app
        run: |
          npx create-next-app@latest my-app --typescript --tailwind --eslint --app --src-dir --import-alias "@/*" --use-pnpm --yes

      - name: Add Shadcn component
        working-directory: ./my-app
        run: |
          pnpm dlx shadcn@latest add @ncdai/slide-to-unlock -y

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Setup Next.js app with slide-to-unlock component"
          git push
